from pathlib import Path
import subprocess
import time
import argparse
import json


SUPPORTED_INPUT_SUFFIXES = {".pdb", ".ply", ".off"}
SURFACE_INPUT_SUFFIXES = {".ply", ".off"}


def convert_old_nnconv_checkpoint_state_dict(state_dict):
    key_mapping = {
        "fc1.weight": "mlp.0.weight",
        "fc1.bias": "mlp.0.bias",
        "fc2.weight": "mlp.1.weight",
        "fc2.bias": "mlp.1.bias",
        "fc3.weight": "mlp.2.weight",
        "fc3.bias": "mlp.2.bias",

        "bn1.weight": "bns.0.weight",
        "bn1.bias": "bns.0.bias",
        "bn1.running_mean": "bns.0.running_mean",
        "bn1.running_var": "bns.0.running_var",

        "bn2.weight": "bns.1.weight",
        "bn2.bias": "bns.1.bias",
        "bn2.running_mean": "bns.1.running_mean",
        "bn2.running_var": "bns.1.running_var",

        "bn3.weight": "bns.2.weight",
        "bn3.bias": "bns.2.bias",
        "bn3.running_mean": "bns.2.running_mean",
        "bn3.running_var": "bns.2.running_var",
    }

    new_state_dict = {}

    for key, value in state_dict.items():
        if key in key_mapping:
            new_state_dict[key_mapping[key]] = value
        elif "num_batches_tracked" in key:
            # souvent inutile, PyTorch peut le recréer
            continue
        else:
            new_state_dict[key] = value

    return new_state_dict

def generate_surface_from_single_pdb(
    pdb_path: str | Path,
    output_dir: str | Path | None = None,
    edtsurf_bin: str = "EDTSurf_mac",
    surface_type: int = 3,
    probe_radius: float = 1.4,
    triangulation_type: int = 2,
    color_mode: int = 2,
    inner_outer: int = 1,
    scale_factor: float = 4.0,
    use_rosetta_arch: bool = True,
    clean_non_ply: bool = True,
) -> Path:
    """
    Generate one .ply surface from one .pdb file using EDTSurf.

    Parameters
    ----------
    pdb_path : str | Path
        Path to the input .pdb file.

    output_dir : str | Path | None
        Directory where the .ply file will be saved.
        If None, output is saved next to the input PDB file.

    edtsurf_bin : str
        EDTSurf executable name or path.
        Example: "EDTSurf_mac" or "utils/EDTSurf_mac".

    surface_type : int
        EDTSurf surface type:
        1 = VWS
        2 = SAS
        3 = MS
        4 = SES

    probe_radius : float
        Probe radius.

    triangulation_type : int
        Triangulation type.

    color_mode : int
        Color mode.

    inner_outer : int
        Inner/outer surface output mode.

    scale_factor : float
        Scale factor.

    use_rosetta_arch : bool
        If True, uses: arch -x86_64 EDTSurf_mac
        Useful on Apple Silicon macOS when EDTSurf requires Rosetta.

    clean_non_ply : bool
        If True, removes non-.ply files generated by EDTSurf in output_dir.

    Returns
    -------
    Path
        Path to the generated .ply file.
    """

    start_time = time.time()

    pdb_path = Path(pdb_path)

    if not pdb_path.exists():
        raise FileNotFoundError(f"PDB file not found: {pdb_path}")

    if pdb_path.suffix.lower() != ".pdb":
        raise ValueError(f"Input file must be a .pdb file: {pdb_path}")

    if output_dir is None:
        output_dir = pdb_path.parent
    else:
        output_dir = Path(output_dir)

    output_dir.mkdir(parents=True, exist_ok=True)

    edtsurf_path = Path(edtsurf_bin)

    if not edtsurf_path.exists():
        raise FileNotFoundError(f"EDTSurf executable not found: {edtsurf_path}")

    output_prefix = output_dir / pdb_path.stem
    expected_ply_path = output_dir / f"{pdb_path.stem}.ply"

    cmd = [
        str(edtsurf_path.resolve()),
        "-i", str(pdb_path.resolve()),
        "-o", str(output_prefix.resolve()),
        "-t", str(triangulation_type),
        "-s", str(surface_type),
        "-c", str(color_mode),
        "-p", str(probe_radius),
        "-f", str(scale_factor),
        "-h", str(inner_outer),
    ]

    if use_rosetta_arch:
        cmd = ["arch", "-x86_64"] + cmd

    run_failed = False
    error_message = None

    try:
        subprocess.run(
            cmd,
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except subprocess.CalledProcessError as e:
        run_failed = True
        error_message = f"CalledProcessError(returncode={e.returncode})"

    if not expected_ply_path.exists() or expected_ply_path.stat().st_size == 0:
        if error_message is None:
            error_message = "Missing or empty .ply output"

        raise RuntimeError(
            f"EDTSurf failed for {pdb_path.name}: {error_message}"
        )

    if clean_non_ply:
        for path in output_dir.iterdir():
            if path.is_file() and path.suffix.lower() != ".ply":
                path.unlink()

    elapsed_seconds = time.time() - start_time

    print("\nEDTSurf single-file summary")
    print("=" * 40)
    print(f"Input PDB        : {pdb_path.name}")
    print(f"Output PLY       : {expected_ply_path}")
    print(f"Surface type     : {surface_type}")
    print(f"Probe radius     : {probe_radius}")
    print(f"Triangulation    : {triangulation_type}")
    print(f"Color mode       : {color_mode}")
    print(f"Inner/outer mode : {inner_outer}")
    print(f"Scale factor     : {scale_factor}")
    print(f"Elapsed time     : {elapsed_seconds:.2f} seconds")

    if run_failed:
        print("Warning: EDTSurf returned a non-zero code, but the .ply file was generated.")

    return expected_ply_path

def prepare_surface_input(data_path, edtsurf_bin="utils/EDTSurf"):
    data_path = Path(data_path)

    if not data_path.exists():
        raise FileNotFoundError(f"Input file not found: {data_path}")

    suffix = data_path.suffix.lower()

    if suffix == ".pdb":
        return generate_surface_from_single_pdb(
            pdb_path=data_path,
            output_dir="data/surfaces",
            edtsurf_bin=edtsurf_bin,
            use_rosetta_arch=False,
        )

    if suffix in SURFACE_INPUT_SUFFIXES:
        return data_path

    raise ValueError(
        f"Input file must be one of {sorted(SUPPORTED_INPUT_SUFFIXES)}, received: {data_path}"
    )

def load_mesh(mesh_path):
    import trimesh

    mesh = trimesh.load(mesh_path, force="mesh")

    if len(mesh.vertices) == 0 or len(mesh.faces) == 0:
        raise ValueError(f"Mesh has no vertices or faces: {mesh_path}")

    return mesh

def get_reduced_mesh(mesh_path, target_faces=750):
    import open3d as o3d
    import numpy as np

    mesh = load_mesh(mesh_path)
    """
    simplifie avec Open3D
    """
    o3d_mesh = o3d.geometry.TriangleMesh(
        vertices=o3d.utility.Vector3dVector(mesh.vertices),
        triangles=o3d.utility.Vector3iVector(mesh.faces)
    )

    # Simplification (quadric decimation)
    o3d_mesh_simplified = o3d_mesh.simplify_quadric_decimation(target_faces)

    # Conversion en Trimesh pour la suite du pipeline
    simplified_mesh = trimesh.Trimesh(
        vertices=np.asarray(o3d_mesh_simplified.vertices),
        faces=np.asarray(o3d_mesh_simplified.triangles)
    )

    return simplified_mesh

def get_graph_data_from_mesh(mesh_red):
    import numpy as np
    import torch
    from torch_geometric.data import Data

    vertices = np.asarray(mesh_red.vertices, dtype=np.float32)   # (N, 3)
    faces = np.asarray(mesh_red.faces, dtype=np.int64)           # (F, 3)


    if vertices.ndim != 2 or vertices.shape[1] != 3:
        raise ValueError(f"vertices doit être de forme (N, 3), reçu {vertices.shape}")

    if faces.ndim != 2 or faces.shape[1] != 3:
        raise ValueError(f"faces doit être de forme (F, 3), reçu {faces.shape}")

    # -----------------------------
    # Node features : [x, y, z, potential]
    # -----------------------------
    x = np.array(vertices).astype(np.float32)  # (N, 4)

    # -----------------------------
    # Normales de faces
    # -----------------------------
    v0 = vertices[faces[:, 0]]
    v1 = vertices[faces[:, 1]]
    v2 = vertices[faces[:, 2]]

    face_normals = np.cross(v1 - v0, v2 - v0)  # (F, 3)
    norms = np.linalg.norm(face_normals, axis=1, keepdims=True)
    norms = np.clip(norms, 1e-12, None)
    face_normals = face_normals / norms

    # -----------------------------
    # Construction des arêtes uniques
    # edge -> faces adjacentes
    # -----------------------------
    edge_to_faces = {}

    for f_idx, (i, j, k) in enumerate(faces):
        tri_edges = [(i, j), (j, k), (k, i)]

        for a, b in tri_edges:
            if a > b:
                a, b = b, a
            key = (a, b)

            if key not in edge_to_faces:
                edge_to_faces[key] = []
            edge_to_faces[key].append(f_idx)

    # tri lexicographique global
    edges = np.array(sorted(edge_to_faces.keys()), dtype=np.int64)  # (E, 2)

    # -----------------------------
    # Degrés des nœuds
    # -----------------------------
    num_nodes = vertices.shape[0]
    degrees = np.zeros(num_nodes, dtype=np.int64)

    for a, b in edges:
        degrees[a] += 1
        degrees[b] += 1

    # -----------------------------
    # Angle dièdre signé en degrés [-180, 180]
    # -----------------------------
    dihedral_angles = np.zeros(len(edges), dtype=np.float32)

    for e_idx, (a, b) in enumerate(edges):
        adjacent_faces = edge_to_faces[(a, b)]

        # arête frontière ou cas dégénéré
        if len(adjacent_faces) < 2:
            dihedral_angles[e_idx] = 0.0
            continue

        f1, f2 = adjacent_faces[:2]
        n1 = face_normals[f1]
        n2 = face_normals[f2]

        edge_vec = vertices[b] - vertices[a]
        edge_norm = np.linalg.norm(edge_vec)

        if edge_norm < 1e-12:
            dihedral_angles[e_idx] = 0.0
            continue

        edge_unit = edge_vec / edge_norm

        sin_term = np.dot(np.cross(n1, n2), edge_unit)
        cos_term = np.clip(np.dot(n1, n2), -1.0, 1.0)

        angle_rad = np.arctan2(sin_term, cos_term)   # [-pi, pi]
        angle_deg = np.degrees(angle_rad)            # [-180, 180]

        dihedral_angles[e_idx] = angle_deg

    # -----------------------------
    # Edge attributes :
    # [signed_dihedral_deg, degree(a), degree(b)]
    # -----------------------------
    edge_attr = np.column_stack([
        dihedral_angles,
        degrees[edges[:, 0]].astype(np.float32),
        degrees[edges[:, 1]].astype(np.float32),
    ]).astype(np.float32)

    # edge_index : (2, E)
    edge_index = edges.T

    graph_data = Data(
        x=torch.tensor(x, dtype=torch.float),
        edge_index=torch.tensor(edge_index, dtype=torch.long),
        edge_attr=torch.tensor(edge_attr, dtype=torch.float),
    )

    return graph_data

def get_graph(mesh_path, target_faces=750):
    return get_graph_data_from_mesh(get_reduced_mesh(mesh_path, target_faces=target_faces))

def get_graph_without_open3d(mesh_path):
    return get_graph_data_from_mesh(load_mesh(mesh_path))

def get_points(mesh_path, n_points=1024):
    import torch

    mesh = load_mesh(mesh_path)

    points = mesh.sample(n_points)

    return torch.from_numpy(points.T).unsqueeze(0).float()

def detect_device():
    import torch

    if torch.cuda.is_available():
        return "cuda"
    if torch.backends.mps.is_available():
        return "mps"
    return "cpu"

def main(
    model_name,
    data_path,
    device=None,
    edtsurf_bin="utils/EDTSurf",
):
    import torch
    from models.models import get_model_architecture

    if device is None:
        device = detect_device()
    device = torch.device(device)

    input_path = Path(data_path)
    surface_path = prepare_surface_input(input_path, edtsurf_bin=edtsurf_bin)
    input_is_precomputed_surface = input_path.suffix.lower() in SURFACE_INPUT_SUFFIXES

    best_model_dict = torch.load(
        f"models/best_models/{model_name}.pt",
        map_location=device,
        weights_only=False,
    )

    if model_name.startswith("PointNet"):
        model_params = {}
    else:
        with open(f"models/best_models/{model_name}.json", "r") as file:
            model_params = json.load(file)["MODEL"]

    model, _ = get_model_architecture(
        model_name,
        99,
        "Ph" in model_name,
        model_params=model_params,
    )

    if model_name.startswith("EE"):
        best_model_dict = convert_old_nnconv_checkpoint_state_dict(best_model_dict)

    model.load_state_dict(best_model_dict, strict=True)
    model = model.to(device)
    model.eval()

    with torch.no_grad():

        if model_name.startswith("PointNet"):
            data = get_points(surface_path, n_points=1024).to(device)
            outputs, embds = model(data)

        elif model_name.startswith("SFM"):
            if input_is_precomputed_surface:
                data = get_graph_without_open3d(surface_path).to(device)
            else:
                data = get_graph(surface_path, target_faces=750).to(device)

            batch = torch.zeros(
                data.x.shape[0],
                dtype=torch.long,
                device=device,
            )

            outputs, embds = model(
                data.x,
                data.edge_index,
                batch,
            )

        elif model_name.startswith("EE"):
            if input_is_precomputed_surface:
                data = get_graph_without_open3d(surface_path).to(device)
            else:
                data = get_graph(surface_path, target_faces=750).to(device)

            batch = torch.zeros(
                data.x.shape[0],
                dtype=torch.long,
                device=device,
            )

            outputs, embds = model(
                data.x,
                data.edge_index,
                data.edge_attr,
                batch,
            )

        else:
            raise ValueError(f"Unknown model name: {model_name}")

    return outputs, embds




if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--model_name",
        type=str,
        required=True,
        help="Model name, e.g. PointNet, SFM, EE_Mesh",
    )
    parser.add_argument(
        "--data_path",
        type=str,
        required=True,
        help="Path to the input .pdb, .ply, or .off file",
    )
    args = parser.parse_args()

    outputs, embds = main(
        model_name=args.model_name,
        data_path=args.data_path,
        device=detect_device(),
        edtsurf_bin="utils/EDTSurf",
    )
